In [1]:
import numpy as np
np_array_1d = np.array([0,2,4,6,8,10])# defining 1d array

In [2]:
np_array_1d

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.sum(np_array_1d)# sum funtion in numpy

30

In [4]:
np_array_2x3 = np.array([[0,2,4],[1,3,5]])# defining 2d array

In [5]:
np_array_2x3#printing 2d array

array([[0, 2, 4],
       [1, 3, 5]])

In [6]:
np.sum(np_array_2x3)# print sum of array elements

15

In [7]:
np_array_2x3 = np.array([[0,2,4],[1,3,5]])

In [8]:
np_array_2x3

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
np.sum(np_array_2x3, axis = 0)# parameters of sum function sum(array,axis(optional),datatype(optional))
                                #if axis=0 represents addition according to rows
                                #if axis =1 represents addition according to col
                                #datatype can be int,float..

array([1, 5, 9])

In [10]:
np.sum(np_array_2x3, axis = 1)#adding elements according to col

array([6, 9])

In [11]:
np.minimum([2, 3, 4], [1, 5, 2])# minimum function finds the minimum elements according to row by default..

array([1, 3, 2])

In [12]:
np.maximum([2, 3, 4], [1, 5, 2])#mximum function finds the maximum elements according to row by default..

array([2, 5, 4])

In [13]:
a = np.array([[1,2,3], [4,5,6]])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.cumsum(a)# this function performs the cumulative sum
            #axis and datatype is not specified here

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [16]:
np.cumsum(a, dtype=float)# gives cumulative sum in float

array([ 1.,  3.,  6., 10., 15., 21.])

In [17]:
np.cumsum(a,axis=0)# performs cumsum according to row

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [18]:
np.cumsum(a,axis=1)# performs cumsum according to col

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [19]:
a = np.array([[1, 2], [3, 4]])

In [20]:
np.mean(a)# performs mean operation according to row by default

2.5

In [21]:
np.mean(a, axis=0)# here axis is specified so it performs mean operation according to row

array([2., 3.])

In [22]:
np.mean(a, axis=1)# here axis is specified so it performs mean operation according to col

array([1.5, 3.5])

In [23]:
np.mean(a, dtype=np.float64)# datatype is specified as float64 to get more precise value

2.5

In [24]:
a = np.array([[10, 7, 4], [3, 2, 1]])

In [25]:
np.median(a)# performs median operation according to row by default

3.5

In [26]:
np.median(a, axis=0)# axis=0 ,according to row

array([6.5, 4.5, 2.5])

In [27]:
np.median(a, axis=1)# axis =1,according to col

array([7., 2.])

In [28]:
a = np.array([[1, 2], [3, 4]])

In [29]:
np.std(a)# performs std deviation 

1.118033988749895

In [30]:
np.std(a, axis=0)# performs std deviation according to row

array([1., 1.])

In [31]:
np.std(a, axis=1)# perform std deviation according to col

array([0.5, 0.5])

In [32]:
np.std(a, dtype=np.float64) #datatype is specified to get more precise value

1.118033988749895